// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9EavR6BYbasB7Jnq17yV5V1wtQIIifE',
    appId: '1:115960683515:web:91379c4fd5012e5291895e',
    messagingSenderId: '115960683515',
    projectId: 'uniride-b30f0',
    authDomain: 'uniride-b30f0.firebaseapp.com',
    storageBucket: 'uniride-b30f0.firebasestorage.app',
    measurementId: 'G-5MK04R1N92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOkdlSfMJ_3VfzH5_MbflmnjHbxZVmZ0',
    appId: '1:115960683515:android:1e2ec58e54f7252291895e',
    messagingSenderId: '115960683515',
    projectId: 'uniride-b30f0',
    storageBucket: 'uniride-b30f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUKg6Al0R7JHTs1K_L_yZyeDNZAMxFPRg',
    appId: '1:115960683515:ios:85ac089e37d288f991895e',
    messagingSenderId: '115960683515',
    projectId: 'uniride-b30f0',
    storageBucket: 'uniride-b30f0.firebasestorage.app',
    iosBundleId: 'com.example.unirideNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUKg6Al0R7JHTs1K_L_yZyeDNZAMxFPRg',
    appId: '1:115960683515:ios:85ac089e37d288f991895e',
    messagingSenderId: '115960683515',
    projectId: 'uniride-b30f0',
    storageBucket: 'uniride-b30f0.firebasestorage.app',
    iosBundleId: 'com.example.unirideNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY9EavR6BYbasB7Jnq17yV5V1wtQIIifE',
    appId: '1:115960683515:web:a6bf613264c22b6891895e',
    messagingSenderId: '115960683515',
    projectId: 'uniride-b30f0',
    authDomain: 'uniride-b30f0.firebaseapp.com',
    storageBucket: 'uniride-b30f0.firebasestorage.app',
    measurementId: 'G-BH78WW3VEM',
  );
}
